#ifndef JPKEYBOARD_GLOBAL_H
#define JPKEYBOARD_GLOBAL_H

#if defined(JPKEYBOARD_LIBRARY)
#  define JPKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JPKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JPKEYBOARD_GLOBAL_H
